// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: blocks.sql

package dbq

import (
	"context"
	"database/sql"
)

const deleteBlock = `-- name: DeleteBlock :execresult
DELETE FROM blocks WHERE id = ?
`

func (q *Queries) DeleteBlock(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteBlock, id)
}

const getBlock = `-- name: GetBlock :one
SELECT id, task_id, start_at_ms, end_at_ms, note, created_at_ms FROM blocks WHERE id = ?
`

func (q *Queries) GetBlock(ctx context.Context, id string) (Block, error) {
	row := q.db.QueryRowContext(ctx, getBlock, id)
	var i Block
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.StartAtMs,
		&i.EndAtMs,
		&i.Note,
		&i.CreatedAtMs,
	)
	return i, err
}

const insertBlock = `-- name: InsertBlock :exec
INSERT INTO blocks (id, task_id, start_at_ms, end_at_ms, note, created_at_ms)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertBlockParams struct {
	ID          string `json:"id"`
	TaskID      string `json:"taskId"`
	StartAtMs   int64  `json:"startAtMs"`
	EndAtMs     int64  `json:"endAtMs"`
	Note        string `json:"note"`
	CreatedAtMs int64  `json:"createdAtMs"`
}

func (q *Queries) InsertBlock(ctx context.Context, arg InsertBlockParams) error {
	_, err := q.db.ExecContext(ctx, insertBlock,
		arg.ID,
		arg.TaskID,
		arg.StartAtMs,
		arg.EndAtMs,
		arg.Note,
		arg.CreatedAtMs,
	)
	return err
}

const listBlocks = `-- name: ListBlocks :many
SELECT id, task_id, start_at_ms, end_at_ms, note, created_at_ms FROM blocks ORDER BY start_at_ms
`

func (q *Queries) ListBlocks(ctx context.Context) ([]Block, error) {
	rows, err := q.db.QueryContext(ctx, listBlocks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Block
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.StartAtMs,
			&i.EndAtMs,
			&i.Note,
			&i.CreatedAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlocksByRange = `-- name: ListBlocksByRange :many
SELECT id, task_id, start_at_ms, end_at_ms, note, created_at_ms FROM blocks WHERE end_at_ms > ? AND start_at_ms < ? ORDER BY start_at_ms
`

type ListBlocksByRangeParams struct {
	EndAtMs   int64 `json:"endAtMs"`
	StartAtMs int64 `json:"startAtMs"`
}

func (q *Queries) ListBlocksByRange(ctx context.Context, arg ListBlocksByRangeParams) ([]Block, error) {
	rows, err := q.db.QueryContext(ctx, listBlocksByRange, arg.EndAtMs, arg.StartAtMs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Block
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.StartAtMs,
			&i.EndAtMs,
			&i.Note,
			&i.CreatedAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlocksByTask = `-- name: ListBlocksByTask :many
SELECT id, task_id, start_at_ms, end_at_ms, note, created_at_ms FROM blocks WHERE task_id = ? ORDER BY start_at_ms
`

func (q *Queries) ListBlocksByTask(ctx context.Context, taskID string) ([]Block, error) {
	rows, err := q.db.QueryContext(ctx, listBlocksByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Block
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.StartAtMs,
			&i.EndAtMs,
			&i.Note,
			&i.CreatedAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlocksByTaskAndRange = `-- name: ListBlocksByTaskAndRange :many
SELECT id, task_id, start_at_ms, end_at_ms, note, created_at_ms FROM blocks WHERE task_id = ? AND end_at_ms > ? AND start_at_ms < ? ORDER BY start_at_ms
`

type ListBlocksByTaskAndRangeParams struct {
	TaskID    string `json:"taskId"`
	EndAtMs   int64  `json:"endAtMs"`
	StartAtMs int64  `json:"startAtMs"`
}

func (q *Queries) ListBlocksByTaskAndRange(ctx context.Context, arg ListBlocksByTaskAndRangeParams) ([]Block, error) {
	rows, err := q.db.QueryContext(ctx, listBlocksByTaskAndRange, arg.TaskID, arg.EndAtMs, arg.StartAtMs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Block
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.StartAtMs,
			&i.EndAtMs,
			&i.Note,
			&i.CreatedAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
