// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: links.sql

package dbq

import (
	"context"
	"database/sql"
)

const deleteLink = `-- name: DeleteLink :execresult
DELETE FROM links WHERE id = ?
`

func (q *Queries) DeleteLink(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteLink, id)
}

const getLink = `-- name: GetLink :one
SELECT id, url, title, description, tags, created_at_ms, updated_at_ms FROM links WHERE id = ?
`

func (q *Queries) GetLink(ctx context.Context, id string) (Link, error) {
	row := q.db.QueryRowContext(ctx, getLink, id)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.URL,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.CreatedAtMs,
		&i.UpdatedAtMs,
	)
	return i, err
}

const insertLink = `-- name: InsertLink :exec
INSERT INTO links (id, url, title, description, tags, created_at_ms, updated_at_ms)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertLinkParams struct {
	ID          string `json:"id"`
	URL         string `json:"url"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Tags        string `json:"tags"`
	CreatedAtMs int64  `json:"createdAtMs"`
	UpdatedAtMs int64  `json:"updatedAtMs"`
}

func (q *Queries) InsertLink(ctx context.Context, arg InsertLinkParams) error {
	_, err := q.db.ExecContext(ctx, insertLink,
		arg.ID,
		arg.URL,
		arg.Title,
		arg.Description,
		arg.Tags,
		arg.CreatedAtMs,
		arg.UpdatedAtMs,
	)
	return err
}

const listLinks = `-- name: ListLinks :many
SELECT id, url, title, description, tags, created_at_ms, updated_at_ms FROM links ORDER BY created_at_ms DESC
`

func (q *Queries) ListLinks(ctx context.Context) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, listLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.URL,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.CreatedAtMs,
			&i.UpdatedAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLink = `-- name: UpdateLink :exec
UPDATE links SET url=?, title=?, description=?, tags=?, updated_at_ms=? WHERE id=?
`

type UpdateLinkParams struct {
	URL         string `json:"url"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Tags        string `json:"tags"`
	UpdatedAtMs int64  `json:"updatedAtMs"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) error {
	_, err := q.db.ExecContext(ctx, updateLink,
		arg.URL,
		arg.Title,
		arg.Description,
		arg.Tags,
		arg.UpdatedAtMs,
		arg.ID,
	)
	return err
}
