// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbq

import (
	"database/sql"
)

type Block struct {
	ID          string `json:"id"`
	TaskID      string `json:"taskId"`
	StartAtMs   int64  `json:"startAtMs"`
	EndAtMs     int64  `json:"endAtMs"`
	Note        string `json:"note"`
	CreatedAtMs int64  `json:"createdAtMs"`
}

type Link struct {
	ID          string `json:"id"`
	Url         string `json:"url"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Tags        string `json:"tags"`
	CreatedAtMs int64  `json:"createdAtMs"`
	UpdatedAtMs int64  `json:"updatedAtMs"`
}

type Task struct {
	ID          string        `json:"id"`
	Title       string        `json:"title"`
	Description string        `json:"description"`
	Status      string        `json:"status"`
	Priority    string        `json:"priority"`
	Due         string        `json:"due"`
	Recurrence  string        `json:"recurrence"`
	Tags        string        `json:"tags"`
	Reminders   string        `json:"reminders"`
	ParentID    string        `json:"parentId"`
	SortOrder   float64       `json:"sortOrder"`
	CreatedAtMs int64         `json:"createdAtMs"`
	UpdatedAtMs int64         `json:"updatedAtMs"`
	DoneAtMs    sql.NullInt64 `json:"doneAtMs"`
}
