// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: slots.sql

package dbq

import (
	"context"
	"database/sql"
)

const deleteSlot = `-- name: DeleteSlot :execresult
DELETE FROM slots WHERE id = ?
`

func (q *Queries) DeleteSlot(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteSlot, id)
}

const getSlot = `-- name: GetSlot :one
SELECT id, task_id, start_at_ms, end_at_ms, note, created_at_ms FROM slots WHERE id = ?
`

func (q *Queries) GetSlot(ctx context.Context, id string) (Slot, error) {
	row := q.db.QueryRowContext(ctx, getSlot, id)
	var i Slot
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.StartAtMs,
		&i.EndAtMs,
		&i.Note,
		&i.CreatedAtMs,
	)
	return i, err
}

const insertSlot = `-- name: InsertSlot :exec
INSERT INTO slots (id, task_id, start_at_ms, end_at_ms, note, created_at_ms)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertSlotParams struct {
	ID          string `json:"id"`
	TaskID      string `json:"taskId"`
	StartAtMs   int64  `json:"startAtMs"`
	EndAtMs     int64  `json:"endAtMs"`
	Note        string `json:"note"`
	CreatedAtMs int64  `json:"createdAtMs"`
}

func (q *Queries) InsertSlot(ctx context.Context, arg InsertSlotParams) error {
	_, err := q.db.ExecContext(ctx, insertSlot,
		arg.ID,
		arg.TaskID,
		arg.StartAtMs,
		arg.EndAtMs,
		arg.Note,
		arg.CreatedAtMs,
	)
	return err
}

const listSlots = `-- name: ListSlots :many
SELECT id, task_id, start_at_ms, end_at_ms, note, created_at_ms FROM slots ORDER BY start_at_ms
`

func (q *Queries) ListSlots(ctx context.Context) ([]Slot, error) {
	rows, err := q.db.QueryContext(ctx, listSlots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Slot
	for rows.Next() {
		var i Slot
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.StartAtMs,
			&i.EndAtMs,
			&i.Note,
			&i.CreatedAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlotsByRange = `-- name: ListSlotsByRange :many
SELECT id, task_id, start_at_ms, end_at_ms, note, created_at_ms FROM slots WHERE end_at_ms > ? AND start_at_ms < ? ORDER BY start_at_ms
`

type ListSlotsByRangeParams struct {
	EndAtMs   int64 `json:"endAtMs"`
	StartAtMs int64 `json:"startAtMs"`
}

func (q *Queries) ListSlotsByRange(ctx context.Context, arg ListSlotsByRangeParams) ([]Slot, error) {
	rows, err := q.db.QueryContext(ctx, listSlotsByRange, arg.EndAtMs, arg.StartAtMs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Slot
	for rows.Next() {
		var i Slot
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.StartAtMs,
			&i.EndAtMs,
			&i.Note,
			&i.CreatedAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlotsByTask = `-- name: ListSlotsByTask :many
SELECT id, task_id, start_at_ms, end_at_ms, note, created_at_ms FROM slots WHERE task_id = ? ORDER BY start_at_ms
`

func (q *Queries) ListSlotsByTask(ctx context.Context, taskID string) ([]Slot, error) {
	rows, err := q.db.QueryContext(ctx, listSlotsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Slot
	for rows.Next() {
		var i Slot
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.StartAtMs,
			&i.EndAtMs,
			&i.Note,
			&i.CreatedAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlotsByTaskAndRange = `-- name: ListSlotsByTaskAndRange :many
SELECT id, task_id, start_at_ms, end_at_ms, note, created_at_ms FROM slots WHERE task_id = ? AND end_at_ms > ? AND start_at_ms < ? ORDER BY start_at_ms
`

type ListSlotsByTaskAndRangeParams struct {
	TaskID    string `json:"taskId"`
	EndAtMs   int64  `json:"endAtMs"`
	StartAtMs int64  `json:"startAtMs"`
}

func (q *Queries) ListSlotsByTaskAndRange(ctx context.Context, arg ListSlotsByTaskAndRangeParams) ([]Slot, error) {
	rows, err := q.db.QueryContext(ctx, listSlotsByTaskAndRange, arg.TaskID, arg.EndAtMs, arg.StartAtMs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Slot
	for rows.Next() {
		var i Slot
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.StartAtMs,
			&i.EndAtMs,
			&i.Note,
			&i.CreatedAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
