// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tasks.sql

package dbq

import (
	"context"
	"database/sql"
)

const completeTask = `-- name: CompleteTask :exec
UPDATE tasks SET status = 'done', done_at_ms = ?, updated_at_ms = ? WHERE id = ?
`

type CompleteTaskParams struct {
	DoneAtMs    sql.NullInt64 `json:"doneAtMs"`
	UpdatedAtMs int64         `json:"updatedAtMs"`
	ID          string        `json:"id"`
}

func (q *Queries) CompleteTask(ctx context.Context, arg CompleteTaskParams) error {
	_, err := q.db.ExecContext(ctx, completeTask, arg.DoneAtMs, arg.UpdatedAtMs, arg.ID)
	return err
}

const countTasks = `-- name: CountTasks :one
SELECT COUNT(*) FROM tasks
`

func (q *Queries) CountTasks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTasks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTask = `-- name: DeleteTask :execresult
DELETE FROM tasks WHERE id = ?
`

func (q *Queries) DeleteTask(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteTask, id)
}

const deleteTaskChildren = `-- name: DeleteTaskChildren :exec
DELETE FROM tasks WHERE parent_id = ?
`

func (q *Queries) DeleteTaskChildren(ctx context.Context, parentID string) error {
	_, err := q.db.ExecContext(ctx, deleteTaskChildren, parentID)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, title, description, status, priority, due, recurrence, tags, parent_id, sort_order, created_at_ms, updated_at_ms, done_at_ms FROM tasks WHERE id = ?
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Due,
		&i.Recurrence,
		&i.Tags,
		&i.ParentID,
		&i.SortOrder,
		&i.CreatedAtMs,
		&i.UpdatedAtMs,
		&i.DoneAtMs,
	)
	return i, err
}

const insertTask = `-- name: InsertTask :exec
INSERT INTO tasks (id, title, description, status, priority, due, recurrence, tags, parent_id, sort_order, created_at_ms, updated_at_ms, done_at_ms)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertTaskParams struct {
	ID          string        `json:"id"`
	Title       string        `json:"title"`
	Description string        `json:"description"`
	Status      string        `json:"status"`
	Priority    string        `json:"priority"`
	Due         string        `json:"due"`
	Recurrence  string        `json:"recurrence"`
	Tags        string        `json:"tags"`
	ParentID    string        `json:"parentId"`
	SortOrder   float64       `json:"sortOrder"`
	CreatedAtMs int64         `json:"createdAtMs"`
	UpdatedAtMs int64         `json:"updatedAtMs"`
	DoneAtMs    sql.NullInt64 `json:"doneAtMs"`
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) error {
	_, err := q.db.ExecContext(ctx, insertTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.Due,
		arg.Recurrence,
		arg.Tags,
		arg.ParentID,
		arg.SortOrder,
		arg.CreatedAtMs,
		arg.UpdatedAtMs,
		arg.DoneAtMs,
	)
	return err
}

const listTasks = `-- name: ListTasks :many
SELECT id, title, description, status, priority, due, recurrence, tags, parent_id, sort_order, created_at_ms, updated_at_ms, done_at_ms FROM tasks ORDER BY (status = 'done'), CASE priority WHEN 'high' THEN 1 WHEN 'medium' THEN 2 WHEN 'low' THEN 3 ELSE 4 END, sort_order
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Due,
			&i.Recurrence,
			&i.Tags,
			&i.ParentID,
			&i.SortOrder,
			&i.CreatedAtMs,
			&i.UpdatedAtMs,
			&i.DoneAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByStatus = `-- name: ListTasksByStatus :many
SELECT id, title, description, status, priority, due, recurrence, tags, parent_id, sort_order, created_at_ms, updated_at_ms, done_at_ms FROM tasks WHERE status = ? ORDER BY (status = 'done'), CASE priority WHEN 'high' THEN 1 WHEN 'medium' THEN 2 WHEN 'low' THEN 3 ELSE 4 END, sort_order
`

func (q *Queries) ListTasksByStatus(ctx context.Context, status string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Due,
			&i.Recurrence,
			&i.Tags,
			&i.ParentID,
			&i.SortOrder,
			&i.CreatedAtMs,
			&i.UpdatedAtMs,
			&i.DoneAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxTaskOrder = `-- name: MaxTaskOrder :one
SELECT CAST(COALESCE(MAX(sort_order), 0) AS REAL) FROM tasks
`

func (q *Queries) MaxTaskOrder(ctx context.Context) (float64, error) {
	row := q.db.QueryRowContext(ctx, maxTaskOrder)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}
